- name: Ubuntu based Code-Server
  hosts: all
  become: true
  gather_facts: yes
  vars:
    oh_my_zsh_theme: robbyrussell
    oh_my_zsh_plugins:
      - git
      - docker
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    
    users:
      - username: "{{ ansible_user_id }}"
  roles:
    - git
    - gantsign.oh-my-zsh
    - zsh
    - docker
    - node
    - code-server
    