---
bin_dir: /usr/local/bin
lib_dir: /usr/local/lib/code-server
systemd_unit_files_dir: /etc/systemd/system
code_server_url_prefix: https://github.com/cdr/code-server/releases/download
code_server_arch: x86_64
code_server_tar_url: "{{ code_server_url_prefix }}/{{ code_server_ver }}/code-server-{{ code_server_ver }}-linux-{{ code_server_arch }}.tar.gz"
code_server_data_dir_abs: "{{ code_server_data_dir | expanduser }}"
