- name: gghcode env init
  hosts: local
  connection: local
  gather_facts: yes
  vars:
    user_name: "Gyuhwan Kim"
    user_email: "gyuhwan.a.kim@gmail.com"
    oh_my_zsh_theme: ""
    oh_my_zsh_plugins:
      - git
      - zsh-autosuggestions
      - zsh-syntax-highlighting
  roles:
    - git
    - docker
    - role: oh-my-zsh
      users:
        - username: "{{ lookup('env','SUDO_USER') | default('root', true) }}"
