- name: gghcode env init
  hosts: local
  connection: local
  gather_facts: yes
  vars:
    main_user: "{{ lookup('env','SUDO_USER') | default(lookup('env', 'USER'), true) }}"
  roles:
    - role: code-server
      become: yes
      code_server_tls_cert: "/etc/letsencrypt/live/{{ code_server_tls_domain }}/cert.pem"
      code_server_tls_key: "/etc/letsencrypt/live/{{ code_server_tls_domain }}/privkey.pem"

    - role: git
      git_author_name: "Gyuhwan Kim"
      git_author_email: "gyuhwan.a.kim@gmail.com"

    - role: oh-my-zsh
      users:
        - username: "{{ main_user }}"
      oh_my_zsh_theme: ""
      oh_my_zsh_plugins:
        - git
        - zsh-autosuggestions
        - zsh-syntax-highlighting

    - role: docker
      when: skip_docker|bool != true
      become: yes
