- name: gghcode env init
  hosts: local
  connection: local
  gather_facts: yes
  vars:
    skip_docker: false
    skip_code_server: false
    user_name: "Gyuhwan Kim"
    user_email: "gyuhwan.a.kim@gmail.com"
    main_user: "{{ lookup('env','SUDO_USER') | default(lookup('env', 'USER'), true) }}"
    oh_my_zsh_theme: ""
    oh_my_zsh_plugins:
      - git
      - zsh-autosuggestions
      - zsh-syntax-highlighting
  roles:
    - git
    - role: docker
      become: yes
      when: skip_docker == false
    - role: oh-my-zsh
      users:
        - username: "{{ lookup('env','SUDO_USER') | default(lookup('env', 'USER'), true) }}"
    - role: nodejs
      become: yes
    - role: code-server
      certbot_create_command: "certbot certonly --standalone -d {{ cert_item.domains | join(',') }} --noninteractive --agree-tos --email {{ cert_item.email }}"
      certbot_certs: 
      - email: "{{ user_email }}"
        domains:
          - test.ghcode.dev
      when: skip_code_server == false

