- name: gghcode env init
  hosts: local
  connection: local
  gather_facts: yes
  vars:
    main_user: "{{ lookup('env','SUDO_USER') | default(lookup('env', 'USER'), true) }}"
  roles:
    - role: git
      git_author_name: "Gyuhwan Kim"
      git_author_email: "gyuhwan.a.kim@gmail.com"

    - role: oh-my-zsh
      users:
        - username: "{{ main_user }}"
      oh_my_zsh_theme: ""
      oh_my_zsh_plugins:
        - git
        - zsh-autosuggestions
        - zsh-syntax-highlighting

    - role: asdf
      asdf_init_shell: true
      asdf_plugins:
        - name: "python"
        - name: "nodejs"
        - name: "golang"
        - name: "rclone"
        - name: "terraform"
        - name: "kubectl"

    - role: code-server
      when: skip_code_server|bool != true

    - role: docker
      when: skip_docker|bool != true
