---
code_server_env_dir: /etc/code-server
code_server_data_dir: "{{ lookup('env', 'HOME') }}/.config/Code"
code_server_work_dir: "{{ lookup('env', 'HOME') }}"
code_server_host: 0.0.0.0
code_server_port: "{{ 8443 if code_server_tls_enable == true else 8080 }}"
