---
code_server_ver: 2.1698
code_server_full_ver: "{{ code_server_ver }}-vsc1.41.1"
code_server_env_dir: /etc/code-server
code_server_data_dir: "{{ lookup('env', 'HOME') }}/.config/Code"
code_server_work_dir: "{{ lookup('env', 'HOME') }}"
code_server_host: 0.0.0.0
code_server_port: "{{ 8443 if code_server_ssl == true else 8080 }}"
code_server_ssl: false
