version: 2.1
executors:
  terraform:
    docker:
      - image: hashicorp/terraform:0.12.6
    working_directory: /tmp/workspace/terraform
    environment:
      TF_IN_AUTOMATION: true
      TF_INPUT: false

jobs:
  terraform-fmt:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Validate terraform fmt
          command: terraform fmt -recursive -check

  unit-test:
    docker: 
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - restore_cache:
          key: python-requirements-{{ checksum "requirements.txt" }}
          
      - run: 
          name: Install pip dependencies
          command: sudo pip install -r requirements.txt
      - run: 
          name: Run unit-tests
          command: python src/test_ec2_sheduler.py

      - save_cache:
          key: python-requirements-{{ checksum "requirements.txt" }}
          paths:
            - "~/.cache/pip"
  terraform-global-plan:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Create terraform credential
          command: echo "credentials "app.terraform.io" { token = \"$TF_TOKEN\" }" > ~/.terraformrc
      - run:
          name: Terraform api_gateway plan
          command: >-
            sh -c "cd infrastructures/global/api_gateway &&
            terraform init -input=false &&
            terraform plan -input=false"
      - run:
          name: Terraform security_group plan
          command: >-
            sh -c "cd infrastructures/global/security_group &&
            terraform init -input=false &&
            terraform plan -input=false"
      - run:
          name: Terraform lambda plan
          command: >-
            sh -c "cd infrastructures/global/lambda &&
            terraform init -input=false &&
            terraform plan -input=false"

  terraform-mini-plan:
    executor: terraform
    environment:
      TF_IN_AUTOMATION: true
      TF_INPUT: false
      TF_WORKSPACE: mini
    steps:
      - checkout
      - run:
          name: Create terraform credential
          command: echo "credentials "app.terraform.io" { token = \"$TF_TOKEN\" }" > ~/.terraformrc
      - run:
          name: Terraform api_gateway_deployment plan
          command: >-
            sh -c "cd infrastructures/mini/api_gateway_deployment &&
            terraform init &&
            terraform plan"
      - run:
          name: Terraform eip plan
          command: >-
            sh -c "cd infrastructures/mini/eip &&
            terraform init &&
            terraform plan"
      - run:
          name: Terraform ec2 plan
          command: >-
            sh -c "cd infrastructures/mini/ec2 &&
            terraform init &&
            terraform plan -var domain=$CODE_SERVER_DOMAIN -var code_server_password=$CODE_SERVER_PASSWORD"

workflows:
  version: 2
  test-plan-deploy:
    jobs:
      - terraform-fmt
      - unit-test
      - terraform-global-plan:
          requires:
            - terraform-fmt
            - unit-test
      - terraform-mini-plan:
          requires:
            - terraform-global-plan
