version: 2
jobs:
  terraform-fmt:
    docker:
      - image: hashicorp/terraform:0.12.6
    working_directory: /tmp/workspace/terraform
    steps:
      - checkout
      - run:
          name: Validate terraform fmt
          command: terraform fmt -recursive -check

  unit-test:
    docker: 
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - restore_cache:
          key: python-requirements-{{ checksum "requirements.txt" }}
          
      - run: 
          name: Install pip dependencies
          command: sudo pip install -r requirements.txt
      - run: 
          name: Run unit-tests
          command: python src/test_ec2_sheduler.py

      - save_cache:
          key: python-requirements-{{ checksum "requirements.txt" }}
          paths:
            - "~/.cache/pip"

workflows:
  version: 2
  test-plan-deploy:
    jobs:
      - terraform-fmt
      - unit-test
