---
- import_tasks: install.yml

- name: console setup for Debian family distributions
  include_tasks: debian-console-setup.yml
  when: ansible_os_family == 'Debian'

- name: install oh-my-zsh plugins
  become: yes
  import_tasks: plugins.yml

- name: install oh-my-zsh theme
  become: yes
  import_tasks: theme.yml
