---
- name: Add Git APT Repository
  become: true
  apt_repository:
    repo: ppa:git-core/ppa
    state: present

- name: Install latest Vim
  become: true
  apt:
    name: vim
    state: latest
    update_cache: yes

- name: Install Git
  become: true
  apt:
    name: git
    state: latest
    update_cache: yes

- name: Copy user template of Git
  become: true
  template:
    src: .gitconfig.j2
    dest: /etc/gitconfig

- name: Copy vimrc template
  template:
    src: .vimrc.j2
    dest: ~{{ main_user }}/.vimrc
