- name: Add Git APT Repository
  become: true
  apt_repository:
    repo: ppa:git-core/ppa
    state: present

- name: Install Git
  become: true
  apt:
    name: git
    state: latest
    update_cache: yes

- name: Copy user template of Git
  become: true
  template:
    src: .gitconfig
    dest: /etc/gitconfig
