---
- name: Create a code-server directory if it does not exist
  file:
    path: "{{ bin_dir }}"
    state: directory
    mode: 0755

- name: Download code-server binary
  unarchive:
    remote_src: yes
    src: "{{ code_server_tar_url }}"
    dest: "{{ bin_dir }}"
    extra_opts:
      - --strip-components=1
      - --wildcards
      - "*/"

- name: Copy code-server systemd unit file
  template:
    src: code-server.service.j2
    dest: "{{ systemd_unit_files_dir }}/code-server.service"

- name: Create code-server data dir
  file:
    path: "{{ code_server_data_dir }}"
    state: directory

- name: Grant code-server data dir
  file:
    path: "{{ code_server_data_dir }}"
    owner: "{{ main_user }}"
    mode: "755"

- name: Create code-server env dir
  file:
    path: "{{ code_server_env_dir }}"
    state: directory

- name: Create code-server working dir
  file:
    path: "{{ code_server_work_dir }}"
    state: directory

- name: Copy code-server env file
  template:
    src: env.j2
    dest: "{{ code_server_env_dir }}/env"
    mode: 0606
  notify: Restart code-server
