---
- name: Create a code-server directory if it does not exist
  become: yes
  file:
    path: "{{ lib_dir }}"
    state: directory
    mode: 0755

- name: Download code-server binary
  become: yes
  unarchive:
    remote_src: yes
    src: "{{ code_server_tar_url }}"
    dest: "{{ lib_dir }}"
    extra_opts:
      - --strip-components=1
      - --wildcards
      - "*/"

- name: Create code-server binary symbolic link
  become: yes
  file:
    src: "{{ lib_dir }}/bin/code-server"
    dest: "{{ bin_dir }}/code-server"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    state: link

- name: Copy code-server systemd unit file
  become: yes
  template:
    src: code-server.service.j2
    dest: "{{ systemd_unit_files_dir }}/code-server.service"

- name: Create code-server data dir
  file:
    path: "{{ code_server_data_dir }}"
    state: directory

- name: Create code-server env dir
  become: yes
  file:
    path: "{{ code_server_env_dir }}"
    state: directory

- name: Create code-server working dir
  file:
    path: "{{ code_server_work_dir }}"
    state: directory

- name: Copy code-server env file
  become: yes
  template:
    src: env.j2
    dest: "{{ code_server_env_dir }}/env"
    mode: 0606
  notify: Restart code-server
