- name: Setup certbot
  include_role:
    name: certbot
  when:
    - main_domain is defined
    - main_domain != ''

- name: Grant certificate permission
  import_tasks: setup-certbot.yml
  when:
    - main_domain is defined
    - main_domain != ''

- name: Install code-server
  import_tasks: install-code-server.yml
