- name: Install code-server
  become: yes
  import_tasks: install-code-server.yml

- name: Setup certbot
  include_role:
    name: certbot
  # import_tasks: setup-certbot.yml
  # when: domain is defined
