- name: Assert arguments
  assert:
    that:
      - code_server_ver is defined
      - code_server_tls_enable is defined

- name: Assert TLS arguments
  when: code_server_tls_enable|bool == true
  assert:
    that:
      - code_server_tls_domain is defined
      - code_server_tls_domain != ''

- name: Grant certificate permission
  when: code_server_tls_enable|bool == true
  import_tasks: setup-certbot.yml

- name: Install code-server
  import_tasks: install-code-server.yml
